# Site settings
title:              HiQDev
tagline:            We're developing HiPanel and HiDev
email:              team@hiqdev.com
description:        We're developing <a href="/hipanel">HiPanel</a> and <a href="/hidev">HiDev</a>
baseurl:            /
url:                http://hiqdev.com
twitter_username:   hiqsol
github_username:    hiqdev
higlighter:         pygments
gems:               [jekyll-paginate, jekyll-gist]

markdown:           redcarpet
kramdown:
    input: GFM

# Permalinks
permalink:          pretty
#relative_permalinks: true

collections:
    projects:
        output:     true

author:
    name:           Andrii Vasyliev
    url:            http://solex.me/

paginate:           5
