package:
    type:           project
    name:           hiqdev.github.io
    headline:       HiQDev
    title:          HiQDev site
    keywords:       hiqdev, development

vendor:
    name: hiqdev

require:
    hiqdev/hidev-hiqdev: "*"
