package:
    type:           project
    name:           hiqdev.github.io
    headline:       HiQDev
    title:          HiQDev site
    keywords:       hiqdev, development
    year:           2015

require:
    hiqdev/hidev-vendor: "*"
    hiqdev/hidev-php:    "*"
