package:
    type:           project
    name:           hiqdev.github.io
    title:          HiQDev.com
    keywords:       hiqdev, development

require:
    hiqdev/hidev-php:    "*"
    hiqdev/hidev-vendor: "*"
